### ISSUE TITLE
create Cart CRUD

### ISSUE THREAD

**Issue by tiagogeraldi** [tiagogeraldi/geraldi-ecommerce#1]
### Attributes
- user_id: integer
- product_id: integer
- quantity: integer
### TODO List:
- create new branch
- create model and migrations
- create controller
- create views
- create ADMIN menu link to 'carts'
- remove 'NEW' button on view and on routes. Ex: resources :carts, except: [:new, :create]

**Comment by grassiricardo** [comment]
Model prompted, developed ...
