### ISSUE TITLE
Create Customer CRUD

### ISSUE THREAD

**Issue by tiagogeraldi** [tiagogeraldi/geraldi-ecommerce#5]
@GrassiRicardo 

Create model, admin controller and form, considering it's a 'readonly' operation.

Model name: Customer
Attributes:
user:references
name:string
address:string
city:string
state:string
zip_code:string
phone:string

**Comment by grassiricardo** [comment]
@tiagogeraldi 
Create customer crud. Commit - 40eb23c242608945ecd0423bfd5dcbe7e52d49de
